export const USERS = {
  GET: {
    REQUEST: 'GET_USERS_REQUEST',
    SUCCESS: 'GET_USERS_SUCCESS',
    FAILURE: 'GET_USERS_FAILURE',
  },
  GET_USER_REPO_LENGTH: {
    REQUEST: 'GET_USER_REPO_LENGTH_REQUEST',
    SUCCESS: 'GET_USER_REPO_LENGTH_SUCCESS',
    FAILURE: 'GET_USER_REPO_LENGTH_FAILURE',
  },
  SEARCH_USER: {
    REQUEST: 'SEARCH_USER_REQUEST',
    SUCCESS: 'SEARCH_USER_SUCCESS',
    FAILURE: 'SEARCH_USER_FAILURE',
  },
}