export const USERS = {
  GET: {
    REQUEST: 'GET_USERS_REQUEST',
    SUCCESS: 'GET_USERS_SUCCESS',
    FAILURE: 'GET_USERS_FAILURE',
  },
  GET_USER_REPO_LENGTH: {
    REQUEST: 'GET_USER_REPO_LENGTH_REQUEST',
    SUCCESS: 'GET_USER_REPO_LENGTH_SUCCESS',
    FAILURE: 'GET_USER_REPO_LENGTH_FAILURE',
  },
  ADD: {
    REQUEST: 'ADD_USERS_REQUEST',
    SUCCESS: 'ADD_USERS_SUCCESS',
    FAILURE: 'ADD_USERS_FAILURE',
  },
  UPDATE: {
    REQUEST: 'UPDATE_USERS_REQUEST',
    SUCCESS: 'UPDATE_USERS_SUCCESS',
    FAILURE: 'UPDATE_USERS_FAILURE',
  },
  DELETE: {
    REQUEST: 'DELETE_USERS_REQUEST',
    SUCCESS: 'DELETE_USERS_SUCCESS',
    FAILURE: 'DELETE_USERS_FAILURE',
  }
}