export const USER = {
  GET: {
    REQUEST: 'GET_USER_BY_NAME_REQUEST',
    SUCCESS: 'GET_USER_BY_NAME_SUCCESS',
    FAILURE: 'GET_USER_BY_NAME_FAILURE',
  },
  GET_REPO_LIST: {
    REQUEST: 'GET_REPO_BY_NAME_REQUEST',
    SUCCESS: 'GET_REPO_BY_NAME_SUCCESS',
    FAILURE: 'GET_REPO_BY_NAME_FAILURE',
  }
}