export const USER = {
  GET_USER: {
    REQUEST: 'GET_USER_BY_NAME_REQUEST',
    SUCCESS: 'GET_USER_BY_NAME_SUCCESS',
    FAILURE: 'GET_USER_BY_NAME_FAILURE',
  },
  GET_REPO_LIST: {
    REQUEST: 'GET_REPO_BY_NAME_REQUEST',
    SUCCESS: 'GET_REPO_BY_NAME_SUCCESS',
    FAILURE: 'GET_REPO_BY_NAME_FAILURE',
  },
  SEARCH_REPO: {
    REQUEST: 'SEARCH_REPO_REQUEST',
    SUCCESS: 'SEARCH_REPO_SUCCESS',
    FAILURE: 'SEARCH_REPO_FAILURE',
  }
}